### ISSUE TITLE
None of the configured nodes are available

### ISSUE THREAD

**Issue by neilneyman** [codelibs/elasticsearch-river-web#109]
Version 2.0.0 is failing, with the message `None of the configured nodes are available: {#transport#-1}{127.0.0.1}{localhost/127.0.0.1:9300}`

I  know elasticsearch is running and listening on the correct ports.  Do you have any idea what's causing this?

The riverweb logfile looks like this where it fails: 

```
2016-02-09 16:30:10,983 [main] INFO  Lasta Di boot successfully.
2016-02-09 16:30:10,986 [main] INFO    SmartDeploy Mode: Warm Deploy
2016-02-09 16:30:10,986 [main] INFO    Smart Package: org.codelibs.riverweb.app
2016-02-09 16:30:11,002 [main] INFO  Disconnected to elasticsearch:localhost:9300
2016-02-09 16:30:11,093 [main] INFO  [Saint Anna] loaded [], sites []
2016-02-09 16:30:11,901 [main] INFO  [Saint Anna] failed to get node info for {#transport#-1}{127.0.0.1}{localhost/127.0.0.1:9300}, disconnecting...
RemoteTransportException[[Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.liveness.LivenessResponse]]];
  nested: TransportSerialization         Exception[Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.liveness.LivenessResponse]]; 
  nested: NoClassDefFoundError[org/apache/lucene/         search/suggest/Lookup]; 
  nested: ClassNotFoundException[org.apache.lucene.search.suggest.Lookup];
Caused by: TransportSerializationException[Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.liveness.LivenessResponse]]; 
  nested: NoClas sDefFoundError[org/apache/lucene/search/suggest/Lookup];
   nested: ClassNotFoundException[org.apache.lucene.search.suggest.Lookup];
        at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:179)
        at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:138)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)

(snip)

2016-02-09 16:30:11,909 [main] INFO  Connected to localhost:9300
2016-02-09 16:30:11,953 [Thread-0] INFO  Disconnected to elasticsearch:localhost:9300
```

**Comment by marevol** [comment]
Hmm..., it's a problem about elasticsearch version...

**Comment by neilneyman** [comment]
Oh I see, probably it.  This is ES 2.2.0, looks like the river is only compatible up to 2.1.  Any plan for an upcoming version for 2.2 or do I need to use it with 2.1?

Thanks!

**Comment by marevol** [comment]
I'll release it this weekend :)

**Comment by hkhail** [comment]
Hello,

I am using Riverweb 2.2.0 and ES 2.3.1. And I have the same problem

Here is the log file : 

2016-06-17 14:34:40,173 [main] DEBUG using gathering [true]
2016-06-17 14:34:40,231 [main] DEBUG [Overrider] node_sampler_interval[5s]
2016-06-17 14:34:40,275 [main] DEBUG Using select timeout of 500
2016-06-17 14:34:40,276 [main] DEBUG Epoll-bug workaround enabled = false
2016-06-17 14:34:40,331 [main] DEBUG [Overrider] adding address [{#transport#-1}{127.0.0.1}{localhost/127.0.0.1:9300}]
2016-06-17 14:34:40,391 [main] DEBUG [Overrider] connected to node [{#transport#-1}{127.0.0.1}{localhost/127.0.0.1:9300}]
2016-06-17 14:34:40,457 [main] DEBUG [Overrider] connected to node [{webindexer}{LtJH8J4pQyisJvAJ38BqYQ}{10.21.27.55}{localhost/127.0.0.1:9300}]
2016-06-17 14:34:40,458 [main] INFO  Connected to localhost:9300
2016-06-17 14:34:40,476 [main] DEBUG [Overrider] search exists api is deprecated and will be removed in the next major version, use search with size set to 0 and terminate_after set to 1 instead
2016-06-17 14:34:40,502 [elasticsearch[Overrider][transport_client_worker][T#2]{New I/O worker #2}] DEBUG using decoder[VanillaChunkDecoder] 
2016-06-17 14:34:40,541 [main] DEBUG .crawler/data mapping exists.
2016-06-17 14:34:40,541 [main] DEBUG [Overrider] search exists api is deprecated and will be removed in the next major version, use search with size set to 0 and terminate_after set to 1 instead
2016-06-17 14:34:40,550 [main] DEBUG .crawler/queue mapping exists.
2016-06-17 14:34:40,550 [main] DEBUG [Overrider] search exists api is deprecated and will be removed in the next major version, use search with size set to 0 and terminate_after set to 1 instead
2016-06-17 14:34:40,557 [main] DEBUG .crawler/filter mapping exists.
2016-06-17 14:34:40,714 [Thread-0] DEBUG [Overrider] disconnecting from [{webindexer}{LtJH8J4pQyisJvAJ38BqYQ}{10.21.27.55}{localhost/127.0.0.1:9300}] due to explicit disconnect call
2016-06-17 14:34:40,728 [Thread-0] DEBUG [Overrider] disconnecting from [{#transport#-1}{127.0.0.1}{localhost/127.0.0.1:9300}] due to explicit disconnect call
2016-06-17 14:34:40,774 [Thread-0] INFO  Disconnected to mycluster:localhost:9300
2016-06-17 14:34:40,774 [Thread-0] DEBUG Connection manager is shutting down
2016-06-17 14:34:40,774 [Thread-0] DEBUG Connection manager shut down

H.
